// Code generated by mockery v2.46.2. DO NOT EDIT.

package sharded

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockshardPicker is an autogenerated mock type for the ShardPicker type
type MockshardPicker struct {
	mock.Mock
}

type MockshardPicker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockshardPicker) EXPECT() *MockshardPicker_Expecter {
	return &MockshardPicker_Expecter{mock: &_m.Mock}
}

// Pick provides a mock function with given fields: ctx, key
func (_m *MockshardPicker) Pick(ctx context.Context, key string) byte {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Pick")
	}

	var r0 byte
	if rf, ok := ret.Get(0).(func(context.Context, string) byte); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(byte)
	}

	return r0
}

// MockshardPicker_Pick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pick'
type MockshardPicker_Pick_Call struct {
	*mock.Call
}

// Pick is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockshardPicker_Expecter) Pick(ctx interface{}, key interface{}) *MockshardPicker_Pick_Call {
	return &MockshardPicker_Pick_Call{Call: _e.mock.On("Pick", ctx, key)}
}

func (_c *MockshardPicker_Pick_Call) Run(run func(ctx context.Context, key string)) *MockshardPicker_Pick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockshardPicker_Pick_Call) Return(_a0 byte) *MockshardPicker_Pick_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockshardPicker_Pick_Call) RunAndReturn(run func(context.Context, string) byte) *MockshardPicker_Pick_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockshardPicker creates a new instance of MockshardPicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockshardPicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockshardPicker {
	mock := &MockshardPicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
